### ISSUE TITLE
Send only the required data from API to frontend.

### ISSUE THREAD

**Issue by Gauravdarkslayer** [dvstechlabs/Noteslify#217] opened 2022-10-31 15:27 UTC
### What would you like to share?

There are some GET APIs which are sending unnecessary data (which are not required by the frontend), so need to fetch only those fields which are required by the frontend, it will help in user security and it also consumes less network bandwidth.

**Comment by devarshishimpi** [comment] 2023-01-06 09:19
> thevinitgupta

@abhinandanwadwa Could you guide him here? Thanks!

**Comment by abhinandanwadwa** [comment] 2023-01-06 09:54
@thevinitgupta 

So, basically there are various routes which are returning some useless json data, which was not supposed to be returned and was not required in the frontend. For example, look at the line below.

https://github.com/dvstechlabs/Noteslify/blob/8f08361dc59ad8839207498b4f143473f9cc59cd/apps/web/backend/routes/notes.js#L42

Instead of returning the  `newNote` object, it's better to return a message saying, "**successfully added new note!**".

You can find all similar routes which are returning useless data and replace them with success text

**Comment by Gauravdarkslayer** [comment] 2023-01-06 11:11
@thevinitgupta 
I would like to add one more point.
Some routes also returning extra fields which are also not required by the frontend.
So, `.select()` while querying can be used in this case. It will help to retrieve only the required fields from collection.
It takes array of fields in string format.

Example of `.select()` in mongoose: https://mongoosejs.com/docs/queries.html#:~:text=%7D).%0A%20%20select(%7B-,name,-%3A%201%2C
OR
https://www.mongodb.com/docs/manual/tutorial/project-fields-from-query-results/#return-the-specified-fields-and-the-_id-field-only

Example where it's required:
https://github.com/dvstechlabs/Noteslify/blob/8f08361dc59ad8839207498b4f143473f9cc59cd/apps/web/backend/routes/notes.js#L109-L115

Here, its returning whole array of objects which contains sensitive information like secret keys. So, try to select only required information while querying.

**Comment by thevinitgupta** [comment] 2023-01-06 12:20
I agree with @Gauravdarkslayer there are many more endpoints that are returning sensitive data along with the required data, like getting a particular note and update note,etc.

I would like to proceed with this. Could you please assign me?

**Comment by thevinitgupta** [comment] 2023-01-06 12:30
Thanks

**Comment by thevinitgupta** [comment] 2023-01-07 08:08
![image](https://user-images.githubusercontent.com/65801700/211140279-8c615228-cab6-4817-9ef7-2bca3f43b32d.png)
@Gauravdarkslayer I am getting this error on requesting `getallnotes` endpoint.

This issue is with the `decrypt` function.

**Comment by Gauravdarkslayer** [comment] 2023-01-07 09:40
@thevinitgupta You can check out this [link](https://stackoverflow.com/questions/21292142/decrypting-aes256-with-node-js-returns-wrong-final-block-length) 
I guess It's a version issue, so try installing the exact version mentioned in the package.json.

**Comment by thevinitgupta** [comment] 2023-01-07 14:34
I tried cloning the repository again and install with the Node version specified.
Also, tried the solutions in the link provided. 
The issue is still persisting.

Could you check if the issue is with the `crypto` package being used in the `helper.js` file?

**Comment by devarshishimpi** [comment] 2023-01-07 14:54
@Gauravdarkslayer Similar issues on my end, request you to look into it.

**Comment by Gauravdarkslayer** [comment] 2023-01-07 20:25
Here I've created an issue and it's corresponding PR. Have a look. 
https://github.com/dvstechlabs/Noteslify/pull/260

**Comment by devarshishimpi** [comment] 2023-01-08 05:34
> Here I've created an issue and it's corresponding PR. Have a look. #260

Merged @thevinitgupta I think the issue should be sorted now 😁

**Closed** 2023-01-10 05:23 UTC
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
